plugins {
	id 'java'
	id 'org.springframework.boot' version '4.1.0'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.pl'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

ext {
	set('springModulithVersion', "2.1.0")
}

dependencies {

	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'
	implementation 'org.springframework.modulith:spring-modulith-starter-core'
	implementation 'org.springframework.modulith:spring-modulith-starter-jpa'
	implementation 'org.springframework.modulith:spring-modulith-events-core'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.boot:spring-boot-starter-flyway'

	// bucker4j
	implementation 'com.bucket4j:bucket4j-core:8.10.1'
	implementation 'com.github.ben-manes.caffeine:caffeine:3.2.4'

   // Flyway

    implementation 'org.flywaydb:flyway-database-postgresql'

	// swagger
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-api:3.0.3'
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.0.3'

	// jwt
	implementation 'io.jsonwebtoken:jjwt-api:0.13.0'
	implementation 'io.jsonwebtoken:jjwt-impl:0.13.0'
	implementation 'io.jsonwebtoken:jjwt-jackson:0.13.0'

	implementation 'net.datafaker:datafaker:2.7.0'

	runtimeOnly 'org.postgresql:postgresql'

	testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-security-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
	testImplementation 'org.springframework.modulith:spring-modulith-starter-test'
//	testImplementation 'org.springframework.boot:spring-boot-starter-restclient'

	//testImplementation 'org.springframework.modulith::spring-boot-starter-flyway-test'
	testImplementation 'org.testcontainers:testcontainers:2.0.5'
	testImplementation 'org.testcontainers:postgresql:1.21.4'
	testImplementation "org.testcontainers:junit-jupiter:1.21.4"
	testImplementation 'org.springframework.boot:spring-boot-testcontainers'
	testImplementation 'org.awaitility:awaitility'

	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.modulith:spring-modulith-bom:${springModulithVersion}"
	}
}

tasks.named('test') {
	useJUnitPlatform()
}
