$env:JDBC_URL="jdbc:postgresql://localhost:5432/hr_app"
$env:DB_USER="hr_app"
$env:DB_PASSWORD="hr_app"

$env:ORGANIZATIONS="100"
$env:COMPANIES_PER_ORGANIZATION="500"
$env:JOB_DESCRIPTIONS_PER_ORGANIZATION="500"
$env:POSTINGS_PER_ORGANIZATION="500"
$env:CANDIDATES_PER_ORGANIZATION="10000"
$env:APPLICATIONS_PER_ORGANIZATION="20000"
$env:INTERVIEWS_PER_ORGANIZATION="5000"

./gradlew run