spring.application.name=hr-agency-system
server.forward-headers-strategy=framework

app.platform.user=${PLATFORM_USER:root}
app.platform.password=${PLATFORM_PASSWORD:}
app.base.url=${BASE_URL:http://localhost:8080}

# ===================
# Database
# ===================

spring.datasource.url=jdbc:postgresql://${PG_HOST:localhost}:${PG_PORT:5432}/hr_app
spring.datasource.username=${PG_USER:hr_app}
spring.datasource.password=${PG_PASSWORD:hr_app}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===================
# JPA
# ===================

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=${JPA_SHOW_SQL:true}

### SWAGGER
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/docs
springdoc.api-docs.path=/api-spec

# ===================
# Flyway
# ===================

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
jwt.secret=${JWT_SECRET:YourSuperSecretKeyThatIsAtLeast32CharactersLong}

# ===================
# Database Pool
# ===================

spring.datasource.hikari.maximum-pool-size=${DB_POOL_MAX_SIZE:32}
spring.datasource.hikari.minimum-idle=${DB_POOL_MIN_IDLE:8}
spring.datasource.hikari.connection-timeout=${DB_CONNECTION_TIMEOUT:30000}
spring.datasource.hikari.max-lifetime=${DB_MAX_LIFETIME:1800000}

# ===================
# Logging
# ===================

logging.level.root=INFO
logging.level.com.pl.hragency=INFO

### RustFS
rustfs.endpoint= ${RUSTFS_ENDPOINT:http://localhost:9000}
rustfs.access-key=${RUSTFS_ACCESS_KEY:admin}
rustfs.secret-key=${RUSTFS_SECRET_KEY:password}
rustfs.feeds.bucket=${RUSTFS_FEEDS_BUCKET:job-feeds}

##
job-feeds.worker.fixed-delay= 1m
job-feeds.creator.fixed-delay= 10m
job-feeds.cleanup.cron=0 30 * * * *

## actuator
management.endpoints.web.exposure.include=health,info

management.endpoint.health.probes.enabled=true
management.endpoint.health.show-details=never

###
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s

###
### spring.jpa.properties.hibernate.format_sql=${JPA_SHOW_SQL:true}
