spring.application.name=hr-agency-system

# ===================
# Database
# ===================

spring.datasource.url=jdbc:postgresql://localhost:5432/hr_app
spring.datasource.username=hr_app
spring.datasource.password=hr_app
spring.datasource.driver-class-name=org.postgresql.Driver

# ===================
# JPA
# ===================

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=${JPA_SHOW_SQL:true}

### SWAGGER
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/docs
springdoc.api-docs.path=/api-spec

# ===================
# Flyway
# ===================

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
jwt.secret=${JWT_SECRET:YourSuperSecretKeyThatIsAtLeast32CharactersLong}

