package com.pl.hragency.recruitment.timeline.model;

public enum CandidateTimelineType {
    CANDIDATE_CREATED,
    CANDIDATE_UPDATED,
    CANDIDATE_STATUS_CHANGED,
    CANDIDATE_EMAIL_CHANGED,
    CANDIDATE_PHONE_CHANGED,
    CANDIDATE_HIRED,

    APPLICATION_CREATED,
    APPLICATION_STATUS_CHANGED,

    APPLICATION_NOTE_ADDED,

    INTERVIEW_SCHEDULED,
    INTERVIEW_COMPLETED,
    INTERVIEW_CANCELLED,
    INTERVIEW_NO_SHOW
}
